import { useState } from "react";
import { VENUES, SPORTS, CATS } from "../data/mockData";
import $ from "../theme/tokens";
import Shell from "../components/ui/PageShell";

const SearchPage = () => {
  const[q,sQ]=useState("");const res=q?VENUES.filter(v=>v.name.toLowerCase().includes(q.toLowerCase())||v.sport.includes(q.toLowerCase())):[];
  return <Shell title="Search"><div style={{position:"relative",marginBottom:20}}><input value={q} onChange={e=>sQ(e.target.value)} placeholder="Courts, sports, venues…" style={{width:"100%",padding:"15px 18px 15px 46px",background:$.surf,border:`1px solid ${$.bd}`,borderRadius:$.r,fontSize:15,color:$.t1,outline:"none",fontFamily:$.font}}/><span style={{position:"absolute",left:18,top:"50%",transform:"translateY(-50%)",fontSize:16,opacity:.35}}>🔍</span></div>
  <div style={{marginBottom:24}}><h3 style={{fontSize:16,fontWeight:700,margin:"0 0 10px"}}>Browse nearby</h3><div style={{background:$.surf,borderRadius:$.r,height:135,border:`1px solid ${$.bd}`,position:"relative",overflow:"hidden"}}><svg width="100%" height="100%" style={{opacity:.2}}><defs><pattern id="sg" width="24" height="24" patternUnits="userSpaceOnUse"><path d="M24 0L0 0 0 24" fill="none" stroke={$.ac} strokeWidth="0.3"/></pattern></defs><rect width="100%" height="100%" fill="url(#sg)"/></svg>{VENUES.slice(0,6).map((v,i)=>{const s=SPORTS[v.sport];return<div key={i} style={{position:"absolute",left:`${10+i*15}%`,top:`${18+(i%3)*22}%`,width:28,height:28,borderRadius:"50%",background:`${s.hue}22`,border:`2px solid ${s.hue}`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:13,boxShadow:`0 0 10px ${s.hue}30`}}>{s.icon}</div>})}<div style={{position:"absolute",bottom:12,right:16,fontSize:11,color:$.t3,fontWeight:600}}>{VENUES.length} venues</div></div></div>
  <h3 style={{fontSize:16,fontWeight:700,margin:"0 0 10px"}}>Browse all</h3><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,marginBottom:24}}>{CATS.map(c=><div key={c.name} style={{background:`${c.cl}0A`,border:`1px solid ${c.cl}1A`,borderRadius:$.r,padding:18,cursor:"pointer",transition:"all .2s"}}><div style={{fontSize:30,marginBottom:8}}>{c.ic}</div><div style={{fontSize:14,fontWeight:700}}>{c.name}</div><div style={{fontSize:11,color:$.t3,marginTop:4}}>{c.n} venues</div></div>)}</div>
  <h3 style={{fontSize:16,fontWeight:700,margin:"0 0 10px"}}>{q?"Results":"Saved places"}</h3>{q?(res.length?res.map(v=>{const s=SPORTS[v.sport];return<div key={v.id} style={{display:"flex",alignItems:"center",gap:14,padding:"13px 0",borderBottom:`1px solid ${$.bd}`}}><div style={{width:46,height:46,borderRadius:14,background:`${s.hue}10`,border:`1px solid ${s.hue}22`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:22}}>{s.icon}</div><div style={{flex:1}}><div style={{fontSize:14,fontWeight:600}}>{v.name}</div><div style={{fontSize:11,color:$.t3,marginTop:2}}>{v.players} playing · {v.open} open</div></div></div>}):<div style={{textAlign:"center",padding:30,color:$.t3,fontSize:13}}>No results</div>):<div style={{display:"flex",gap:12,overflow:"auto",paddingBottom:8}}>{[1,2,3,4,5].map(i=><div key={i} style={{width:56,height:56,borderRadius:"50%",border:`2px dashed ${$.bl}`,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0,fontSize:18,color:$.t3}}>+</div>)}</div>}
  </Shell>;
};

export default SearchPage;
